masdefry/jcwd300202

apps/web/package.json, apps/web/src/app/auth/register/page.tsx, apps/web/src/app/layout.tsx, apps/web/src/app/order/[order-id]/page.tsx, apps/web/src/components/Header.tsx, apps/web/src/features/order/components/index.tsx, apps/web/tailwind.config.js, package-lock.json
=> feat: header

apps/web/src/app/auth/page.tsx, apps/web/src/app/auth/register/page.tsx, apps/web/src/components/Header.tsx
=> fix: add filtering feature on header

apps/web/src/app/auth/page.tsx, apps/web/src/app/tenant/auth/layout.tsx, apps/web/src/app/tenant/auth/page.tsx, apps/web/src/app/tenant/auth/register/page.tsx, apps/web/src/components/Header.tsx, apps/web/src/features/auth/components/AuthButton.tsx, apps/web/src/features/auth/components/AuthHGroup.tsx, apps/web/src/features/auth/components/Footer.tsx, apps/web/src/features/auth/components/GoogleSignInButton.tsx, apps/web/src/features/auth/components/Separator.tsx, apps/web/src/features/auth/components/TextInput.tsx
Slicing UI for authentication page
=> fix: slicing ui for auth

apps/api/prisma/migrations/20241206040858_add_column_city_and_country/migration.sql, apps/api/prisma/migrations/20241206041549_add_column_country_id_at_table_city/migration.sql, apps/api/prisma/schema.prisma, apps/api/prisma/seed.js, apps/api/src/controllers/auth.controller.ts
Create controller function for login, register, and send verification email
=> feat: create auth controller

apps/api/prisma/migrations/20241206062058_update_column_user_id_table_profile/migration.sql, apps/api/prisma/migrations/20241206071703_update_column_password_table_tenant_and_user/migration.sql, apps/api/prisma/schema.prisma, apps/api/src/controllers/auth.controller.ts
Add table city and country at prisma include seeding
=> feat: add table city and country at prisma

apps/web/src/app/auth/page.tsx, apps/web/src/app/auth/register/page.tsx, apps/web/src/app/auth/verify/[token]/page.tsx, apps/web/src/app/tenant/auth/page.tsx, apps/web/src/app/tenant/auth/register/page.tsx, apps/web/src/app/tenant/auth/verify/[token]/page.tsx, apps/web/src/features/auth/components/TextInput.tsx
Create email verification page for user and tenant with set password
=> feat: create page for email verification

apps/api/prisma/migrations/20241206162734_add_column_table_city/migration.sql, apps/api/prisma/schema.prisma, apps/api/prisma/seed.js, apps/web/src/app/layout.tsx, apps/web/src/app/page.tsx, apps/web/src/components/Footer.tsx, apps/web/src/components/Header.tsx, apps/web/src/features/home/components/CityRecommendationCard.tsx
- Add footer
- Fix header responsivity
- Fix landing page responsivity
=> feat: create footer and page responsiveness

apps/api/src/controllers/auth.controller.ts, apps/api/src/index.ts, apps/api/src/middlewares/tenant.role.validation.ts, apps/api/src/middlewares/uploader.ts, apps/api/src/middlewares/user.role.validation.ts, apps/api/src/middlewares/verify.token.ts, apps/api/src/routers/auth.router.ts, apps/api/src/routers/index.ts, apps/api/src/utils/jwt.ts, apps/api/src/utils/multer.ts, apps/web/next.config.js, apps/web/src/app/page.tsx, apps/web/src/components/Footer.tsx, apps/web/src/components/FooterNav.tsx, apps/web/src/components/FooterSocialMediaList.tsx, apps/web/src/components/FooterSocialMediaSeparator.tsx, apps/web/src/features/home/components/Hero.tsx, apps/web/src/features/home/hooks/useHeroHook.tsx
=> fix: responsive footer

.vscode/settings.json, apps/api/src/controllers/room.controller.ts, apps/api/turbo.json, apps/web/package.json, apps/web/src/app/globals.css, apps/web/src/app/order/[order-id]/page.tsx, apps/web/tsconfig.json, package-lock.json, package.json, turbo.json
=> feat: add room list feature

apps/web/src/app/auth/page.tsx
=> fix: responsive header

apps/api/package.json, apps/api/src/controllers/transaction.controller.ts, apps/api/src/middlewares/validator/error.handling.validator.ts, apps/api/src/middlewares/validator/login.validator.ts, apps/api/src/middlewares/validator/register.validator.ts, apps/api/src/routers/auth.router.ts, apps/web/src/components/Header.tsx, package-lock.json
- Express validator for login user
- Express validator for login tenant
- Express validator for register user
- Express validator for register tenant
=> feat: validator for login and register

apps/api/prisma/schema.prisma, apps/api/src/controllers/transaction.controller.ts, apps/api/src/services/transaction.service/index.ts, apps/api/src/services/transaction.service/types.ts
adding nights, adult, and children into transaction controller and service
=> feat: updating transaction controller

apps/api/src/services/transaction.service/index.ts
adding nights, adult, and children into the transaction history list
=> feat: updating the transaction order list service

apps/api/src/services/transaction.service/index.ts
user can see the updated transaction status
=> feat: update transaction controller to check status

apps/api/src/controllers/header.controller.ts, apps/api/src/index.ts, apps/api/src/routers/header.router.ts, apps/web/src/app/explore/[search]/page.tsx, apps/web/src/components/DropdownCitiesAndCountries.tsx, apps/web/src/components/GuestAndRoomCounter.tsx, apps/web/src/components/Header.tsx, apps/web/src/components/SearchHeader2XLWidth.tsx, apps/web/src/features/home/schemas/searchValidationSchema.ts, apps/web/src/hooks/useSearchHook.tsx, apps/web/src/zustand/searchStore.ts
=> feat: fix search in header

apps/api/src/controllers/property.controller.ts, apps/api/src/routers/property.router.ts, apps/web/package.json, apps/web/src/app/property/[slug]/page.tsx, apps/web/src/components/CardSmall.tsx, apps/web/src/components/SimpleMap.tsx, apps/web/src/features/property/components/ImageCarousel.tsx, apps/web/src/features/property/hooks/useImageCarouselHook.tsx, package-lock.json
- Re-layouting UI for property detail
=> feat: create pagination for room types

apps/web/src/app/explore/[search]/layout.tsx, apps/web/src/app/explore/[search]/page.tsx
=> fix: relayout card of property in explore page

apps/api/src/controllers/header.controller.ts, apps/api/src/controllers/property.controller.ts, apps/api/src/index.ts, apps/api/src/routers/property.router.ts, apps/api/src/services/header.service/index.ts, apps/web/src/app/explore/[search]/cancelled.tsx, apps/web/src/app/explore/[search]/page.tsx, apps/web/src/components/SearchHeader2XLWidth.tsx, apps/web/src/features/property/hooks/useFilteringPropertyHook.tsx
- Integrating explore page with api
- Create pagination for explore page
- Integrated property filtering
=> feat: pagination for explore

apps/api/src/controllers/property.controller.ts, apps/web/package.json, apps/web/src/app/explore/[search]/page.tsx, apps/web/src/components/ui/select.tsx, package-lock.json
- Filtering still have bug when page has refreshed
- Only works for filter property type, property facility, and room facility
=> feat: active some filtering section

apps/web/src/app/user/layout.tsx, apps/web/src/app/user/profile/page.tsx
=> feat: layouting ui for edit user profile

apps/web/src/app/tenant/profile/page.tsx, apps/web/src/features/tenant/profile/schemas/updateTenantProfileValidationSchema.ts
- Create validation schema for tenant profile
=> feat: connecting tenant profile page with api

apps/api/src/controllers/property.controller.ts, apps/api/src/routers/property.router.ts, apps/web/src/app/explore/[search]/page.tsx, apps/web/src/app/page.tsx, apps/web/src/app/property/[slug]/details/loading.tsx, apps/web/src/app/property/[slug]/details/page.tsx, apps/web/src/app/user/layout.tsx, apps/web/src/components/SearchHeader2XLWidth.tsx
=> feat: get parameter from search to property detail

apps/web/src/app/page.tsx, apps/web/src/components/Footer.tsx, apps/web/src/components/FooterNav.tsx, apps/web/src/components/FooterSocialMediaList.tsx, apps/web/src/components/HamburgerMenu.tsx, apps/web/src/components/Header.tsx, apps/web/src/components/Promotion.tsx, apps/web/src/components/SearchHeader.tsx
=> fix: re-layouting header and footer

apps/web/src/app/explore/[search]/page.tsx
=> feat: responsive explore page

.prettierrc, apps/api/src/controllers/landing.page.controller.ts, apps/web/src/app/page.tsx, apps/web/src/app/tenant/layout.tsx, apps/web/src/app/tenant/property/create/page.tsx, apps/web/src/components/Card.tsx, apps/web/src/components/SearchHeader.tsx
=> feat: image preview create property

apps/api/prisma/migrations/20250103055828_add_table_room_filled/migration.sql, apps/api/prisma/schema.prisma, apps/api/src/controllers/property.controller.ts, apps/api/src/controllers/property.room.type.controller.ts, apps/api/src/controllers/season.controller.ts, apps/web/src/app/property/[slug]/details/page.tsx, apps/web/src/app/tenant/layout.tsx, apps/web/src/app/test/page.tsx, apps/web/src/features/property/components/ImageCarousel.tsx
=> feat: seasonal price for property detail

apps/api/src/controllers/auth.controller.ts, apps/api/src/controllers/property.controller.ts, apps/api/src/routers/auth.router.ts, apps/api/src/routers/property.router.ts, apps/web/src/app/auth/reset-password/[token]/page.tsx, apps/web/src/app/auth/reset-password/page.tsx, apps/web/src/app/auth/verify/[token]/page.tsx, apps/web/src/app/auth/verify/request-email/page.tsx, apps/web/src/app/tenant/auth/reset-password/[token]/page.tsx, apps/web/src/app/tenant/auth/reset-password/page.tsx, apps/web/src/app/tenant/auth/verify/[token]/page.tsx, apps/web/src/app/tenant/auth/verify/request-email/page.tsx, apps/web/src/app/tenant/layout.tsx, apps/web/src/app/tenant/profile/page.tsx, apps/web/src/app/tenant/property/create/page.tsx, apps/web/src/app/tenant/property/manage/[slug]/calendar/page.tsx, apps/web/src/app/tenant/property/manage/[slug]/descriptions/page.tsx, apps/web/src/app/tenant/property/manage/[slug]/facilities/page.tsx, apps/web/src/app/tenant/settings/page.tsx, apps/web/src/app/user/profile/page.tsx, apps/web/src/app/user/settings/page.tsx, apps/web/src/features/auth/hooks/useLoginHook.tsx, apps/web/src/features/auth/hooks/useLoginWithGoogleHook.tsx, apps/web/src/features/auth/hooks/useRegisterHook.tsx
- Tenant can update their property descriptions
=> feat: update property descriptions page

apps/api/src/controllers/property.controller.ts, apps/web/src/app/tenant/property/list/page.tsx
=> feat: filtering and sorting for property list
